### ISSUE TITLE
on a mac the script displays sh: cls not found 

### ISSUE THREAD

**Issue by kickstart530** [datta07/Live-Cricket-Scores#1]
Create a fork with docker support and fixed the issue with clear message change for linux support

**Comment by kickstart530** [comment]
https://github.com/kickstart530/Live-Cricket-Scores 

Froked it for personal changes. Thanks for this cool trick! ... this is a good one. 

Thank you.

**Comment by kickstart530** [comment]
Please feel free to take the code as is :) Its full credit to you man and update here.
you are Good!

**Comment by datta07** [comment]
Thanks for this issue and your effots for doing it great.I will soon resolve this issue.

**Comment by datta07** [comment]
Fixed this issue.., Now can be used on any OS. Also fixed inappropriate spacing b/w words. Again thanks for this issue.

**Comment by kickstart530** [comment]
Cool man Good Luck ... Keep Rocking!
