### ISSUE TITLE
Support for other cricket matches and websocket information request

### ISSUE THREAD

**Issue by ScrumpyJack** [datta07/Live-Cricket-Scores#2]
This looks awesome, and I'd like to use it to watch test matches, but I have to ask. What is on the other end of this web socket? wss://criclive-72dee-43d33.firebaseio.com/.ws?ns=criclive-72dee-43d33&v=5
It looks like it's hosted by google. Can we know more about it? Can we adapt it for test matches around the world?

**Comment by datta07** [comment]
This code completely works for all cricket match's which are on live. This code includes all T20,ODI,TEST and even T10 match's. 
this code can handle 5-6 live match's at a time. Schedule to use it on a match day, you can get it.
