### ISSUE TITLE
Feature request: Display the remaining balls in the over

### ISSUE THREAD

**Issue by ScrumpyJack** [datta07/Live-Cricket-Scores#6]
Can you add the remaining balls left in the over to the output? Maybe next to the bowler's name?

**Comment by datta07** [comment]
no, this code is based on the API response, which doesn't have?

**Comment by ScrumpyJack** [comment]
Is the API documented anywhere?

**Comment by ScrumpyJack** [comment]
It looks like in the API response feed there is the number of balls in the over
"ov":"16.2"
The first number is the over and the second number is the ball of the over.

Looks like you output that under the team name

Maybe like this?
```
Over 16. Ball 2. Bowler  : Mohammad Imran
```

**Comment by ScrumpyJack** [comment]
i don't know, maybe it works as it is.

**Comment by datta07** [comment]
okay i got it,I will make it on future update
